"""Markdown rendering (spec F-HUMAN-1, §7.2).

The Markdown is the artifact a GRC reviewer actually reads, so it is written to
be self-contained: system facts, then each inventory section, then the review
notes, then a provenance footer that ties the document back to the exact BOM
digest and rules version. Everything here is derived from the BOM JSON, which
stays the source of truth (`aibom render` regenerates any format from it).
"""

from __future__ import annotations

import json
from typing import Any

from aibom.digest import digest_of

RISK_BADGE = {"high": "🔴 high", "medium": "🟠 medium", "low": "🟢 low", "unknown": "⚪ unknown"}


def _prop_map(component: dict[str, Any]) -> dict[str, str]:
    return {
        p["name"]: p.get("value", "")
        for p in component.get("properties") or []
        if isinstance(p, dict) and p.get("name")
    }


def _esc(text: Any) -> str:
    if text is None:
        return ""
    return str(text).replace("|", "\\|").replace("\n", " ")


def _code(text: Any) -> str:
    return f"`{_esc(text)}`" if text not in (None, "") else "—"


def _yes_no(value: Any, *, yes: str = "yes", no: str = "no") -> str:
    if value in (None, ""):
        return "—"
    truthy = str(value).lower() in {"true", "yes", "1"}
    return yes if truthy else no


def _title_case(text: str) -> str:
    return text.replace("-", " ").replace("_", " ").title()


def _components(bom: dict[str, Any], kind: str) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for item in bom.get("components") or []:
        if not isinstance(item, dict):
            continue
        props = _prop_map(item)
        ctype = item.get("type")
        if kind == "model" and ctype == "machine-learning-model" or kind == "prompt" and ctype == "data" and any(
            isinstance(d, dict) and d.get("classification") == "prompt" for d in item.get("data") or []
        ) or kind == "tool" and ctype == "library" and props.get("aibom:role") != "ai-sdk" or kind == "ai-sdk" and ctype == "library" and props.get("aibom:role") == "ai-sdk":
            out.append(item)
        elif kind == "dataset" and ctype == "data" and props.get("aibom:role") != "retrieval-source":
            if not any(
                isinstance(d, dict) and d.get("classification") == "prompt" for d in item.get("data") or []
            ):
                out.append(item)
        elif kind == "retrieval" and ctype == "data" and props.get("aibom:role") == "retrieval-source":
            out.append(item)
    return out


def _services(bom: dict[str, Any], kind: str) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for item in bom.get("services") or []:
        if not isinstance(item, dict):
            continue
        props = _prop_map(item)
        role = props.get("aibom:role")
        if kind == "provider" and role == "model-provider" or kind == "external" and role == "external-ai-service" or kind == "mcp" and role not in {"model-provider", "external-ai-service"}:
            out.append(item)
    return out


def render_markdown(bom: dict[str, Any]) -> str:
    """Render a CycloneDX AI BOM as `AIBOM.md`."""
    metadata = bom.get("metadata") or {}
    app = metadata.get("component") or {}
    app_props = _prop_map(app)
    digest = digest_of(bom)

    lines: list[str] = []
    lines += _header(app, app_props, bom)
    lines += _system_facts(app, app_props, metadata, bom)
    lines += _models(_components(bom, "model"))
    lines += _tools(_components(bom, "tool"))
    lines += _mcp_and_services(bom)
    lines += _prompts(_components(bom, "prompt"))
    lines += _datasets(_components(bom, "dataset"), _components(bom, "retrieval"))
    lines += _ai_sdks(_components(bom, "ai-sdk"))
    lines += _dependency_graph(bom)
    lines += _review_notes(bom)
    lines += _provenance(bom, app_props, digest)
    return "\n".join(lines).rstrip() + "\n"


def _header(app: dict[str, Any], app_props: dict[str, str], bom: dict[str, Any]) -> list[str]:
    name = app.get("name", "AI system")
    version = app.get("version")
    risk_label = app_props.get("aibom:risk_label")
    framework = app_props.get("aibom:risk_framework")
    subtitle_bits = []
    if version:
        subtitle_bits.append(f"v{version}")
    if risk_label:
        subtitle_bits.append(f"{framework or 'risk'}: {risk_label}")
    if app_props.get("aibom:deployment"):
        subtitle_bits.append(app_props["aibom:deployment"])
    subtitle = " · ".join(subtitle_bits)
    return [
        f"# AI Bill of Materials — {name}",
        "",
        f"> {subtitle}" if subtitle else "",
        "",
        app.get("description", ""),
        "",
        f"**Inventory:** {_inventory_line(bom)}",
        "",
        "<!-- This file is generated by aibom. The CycloneDX JSON is the source of truth. -->",
        "",
    ]


def _inventory_line(bom: dict[str, Any]) -> str:
    counts = {
        "models": len(_components(bom, "model")),
        "prompts": len(_components(bom, "prompt")),
        "tools": len(_components(bom, "tool")),
        "MCP servers": len(_services(bom, "mcp")),
        "providers": len(_services(bom, "provider")),
        "datasets": len(_components(bom, "dataset")),
        "external services": len(_services(bom, "external")),
        "AI SDKs": len(_components(bom, "ai-sdk")),
    }
    return " · ".join(f"{count} {label}" for label, count in counts.items())


def _system_facts(
    app: dict[str, Any], app_props: dict[str, str], metadata: dict[str, Any], bom: dict[str, Any]
) -> list[str]:
    rows: list[tuple[str, Any]] = [
        ("System", app.get("name")),
        ("Version", app.get("version")),
        ("Owner", app_props.get("aibom:owner")),
        ("Purpose", app_props.get("aibom:purpose")),
        ("Deployment", app_props.get("aibom:deployment")),
        ("Data classification", app_props.get("aibom:data_classification")),
        ("Jurisdictions", app_props.get("aibom:jurisdictions")),
        (
            "Risk classification",
            f"{app_props.get('aibom:risk_framework', '')} — {app_props.get('aibom:risk_label', '')}".strip(" —")
            or None,
        ),
        ("Risk rationale", app_props.get("aibom:risk_rationale")),
        ("Human oversight", app_props.get("aibom:human_oversight")),
        ("Generated", metadata.get("timestamp")),
        ("Lifecycle", ", ".join(lc.get("phase", "") for lc in metadata.get("lifecycles") or [])),
    ]
    lines = ["## System", "", "| Field | Value |", "| --- | --- |"]
    for label, value in rows:
        if value not in (None, ""):
            lines.append(f"| {label} | {_esc(value)} |")
    contacts = metadata.get("authors") or []
    if contacts:
        rendered = ", ".join(
            f"{c.get('name', '')}" + (f" <{c['email']}>" if c.get("email") else "") for c in contacts
        )
        lines.append(f"| Contacts | {_esc(rendered)} |")
    lines.append("")
    return lines


def _models(models: list[dict[str, Any]]) -> list[str]:
    if not models:
        return []
    lines = [
        "## Models",
        "",
        "| Model | Version | Pinned | Purpose | Kind | Region | DPA | Retirement | Used at |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for model in models:
        props = _prop_map(model)
        floating = str(props.get("aibom:floating", "")).lower() == "true"
        pinned = "❌ floating" if floating else "✅ pinned"
        lines.append(
            "| {name} | {version} | {pinned} | {purpose} | {kind} | {region} | {dpa} | {ret} | {loc} |".format(
                name=_code(props.get("aibom:alias") or model.get("name")),
                version=_code(model.get("version")),
                pinned=pinned,
                purpose=_esc(props.get("aibom:purpose")),
                kind=_esc(props.get("aibom:kind")),
                region=_esc(props.get("aibom:hosting_region")),
                dpa=_yes_no(props.get("aibom:data_processing_agreement")),
                ret=_esc(props.get("aibom:retirement")),
                loc=_esc(props.get("aibom:locations")),
            )
        )
    lines.append("")
    card_lines = _model_cards(models)
    lines += card_lines
    return lines


def _model_cards(models: list[dict[str, Any]]) -> list[str]:
    out: list[str] = []
    for model in models:
        card = model.get("modelCard") or {}
        props = _prop_map(model)
        considerations = card.get("considerations") or {}
        metrics = (card.get("quantitativeAnalysis") or {}).get("performanceMetrics") or []
        if not (considerations or metrics):
            continue
        out.append(f"### Model card — `{props.get('aibom:alias') or model.get('name')}`")
        out.append("")
        params = card.get("modelParameters") or {}
        if params:
            out.append(
                "**Parameters:** "
                + ", ".join(f"{k}={v}" for k, v in params.items() if v)
            )
            out.append("")
        for key, label in (
            ("useCases", "Intended use cases"),
            ("technicalLimitations", "Technical limitations"),
            ("ethicalConsiderations", "Ethical considerations"),
        ):
            values = considerations.get(key) or []
            if not values:
                continue
            out.append(f"- **{label}:**")
            for value in values:
                if isinstance(value, dict):
                    name = value.get("name", "")
                    mitigation = value.get("mitigationStrategy")
                    out.append(f"  - {name}" + (f" — mitigation: {mitigation}" if mitigation else ""))
                else:
                    out.append(f"  - {value}")
        if metrics:
            out.append("- **Evaluation:**")
            for metric in metrics:
                out.append(f"  - {metric.get('type')}: {metric.get('value', 'n/a')}")
        out.append("")
    return out


def _tools(tools: list[dict[str, Any]]) -> list[str]:
    if not tools:
        return []
    lines = [
        "## Tools",
        "",
        "Risk-sorted. Capabilities come from the versioned rulebook; every verdict is",
        "reproducible with `aibom explain-risk <tool>`.",
        "",
        "| Tool | Risk | Capabilities | HITL | Reversible | Rate-limited | Defined at |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for tool in tools:
        props = _prop_map(tool)
        risk = props.get("aibom:risk", "unknown")
        override = " _(override)_" if props.get("aibom:risk_override") == "true" else ""
        lines.append(
            "| {name} | {risk} | {caps} | {hitl} | {rev} | {rate} | {loc} |".format(
                name=_code(tool.get("name")),
                risk=RISK_BADGE.get(risk, risk) + override,
                caps=_esc(props.get("aibom:capabilities")) or "—",
                hitl=_yes_no(props.get("aibom:human_in_the_loop")),
                rev=_yes_no(props.get("aibom:reversible"), yes="reversible", no="irreversible"),
                rate=_yes_no(props.get("aibom:rate_limited")),
                loc=_code(props.get("aibom:path")),
            )
        )
    lines.append("")
    overrides = [t for t in tools if _prop_map(t).get("aibom:risk_override") == "true"]
    if overrides:
        lines.append("### Risk overrides")
        lines.append("")
        for tool in overrides:
            props = _prop_map(tool)
            lines.append(
                f"- `{tool.get('name')}`: heuristic **{props.get('aibom:heuristic_risk', '?')}** "
                f"overridden to **{props.get('aibom:risk')}** — {props.get('aibom:risk_justification', 'no justification')}"
            )
        lines.append("")
    return lines


def _mcp_and_services(bom: dict[str, Any]) -> list[str]:
    mcp = _services(bom, "mcp")
    providers = _services(bom, "provider")
    external = _services(bom, "external")
    lines: list[str] = []
    if mcp:
        lines += [
            "## MCP servers",
            "",
            "| Server | Transport | Risk | Capabilities | Auth | Pinned | Config |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
        for server in mcp:
            props = _prop_map(server)
            risk = props.get("aibom:risk", "unknown")
            lines.append(
                "| {name} | {transport} | {risk} | {caps} | {auth} | {pinned} | {config} |".format(
                    name=_code(server.get("name")),
                    transport=_code(props.get("aibom:transport")),
                    risk=RISK_BADGE.get(risk, risk),
                    caps=_esc(props.get("aibom:capabilities")) or "—",
                    auth=_yes_no(server.get("authenticated")),
                    pinned=_yes_no(props.get("aibom:version_pinned")),
                    config=_code(props.get("aibom:config")),
                )
            )
        lines.append("")
    if providers:
        lines += [
            "## Model providers",
            "",
            "| Provider | Region | DPA | Data classification | Models |",
            "| --- | --- | --- | --- | --- |",
        ]
        for provider in providers:
            props = _prop_map(provider)
            lines.append(
                "| {name} | {region} | {dpa} | {cls} | {models} |".format(
                    name=_code(provider.get("name")),
                    region=_esc(props.get("aibom:region")),
                    dpa=_yes_no(props.get("aibom:dpa")),
                    cls=_esc(props.get("aibom:data_classification")),
                    models=_esc(props.get("aibom:models")),
                )
            )
        lines.append("")
    if external:
        lines += [
            "## External AI services",
            "",
            "| Service | Provider | Purpose | Data shared | DPA | Region |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for service in external:
            props = _prop_map(service)
            lines.append(
                "| {name} | {provider} | {purpose} | {shared} | {dpa} | {region} |".format(
                    name=_code(service.get("name")),
                    provider=_esc(props.get("aibom:provider")),
                    purpose=_esc(props.get("aibom:purpose")),
                    shared=_esc(props.get("aibom:data_shared")),
                    dpa=_yes_no(props.get("aibom:dpa")),
                    region=_esc(props.get("aibom:region")),
                )
            )
        lines.append("")
    return lines


def _prompts(prompts: list[dict[str, Any]]) -> list[str]:
    if not prompts:
        return []
    lines = [
        "## Prompts",
        "",
        "| Prompt | Path | Line | ~Tokens | Source | Owners | SHA-256 |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for prompt in prompts:
        props = _prop_map(prompt)
        digest = next(
            (h.get("content", "") for h in prompt.get("hashes") or [] if h.get("alg") == "SHA-256"),
            "",
        )
        lines.append(
            "| {name} | {path} | {line} | {tokens} | {source} | {owners} | {digest} |".format(
                name=_code(prompt.get("name")),
                path=_code(props.get("aibom:path")),
                line=_esc(props.get("aibom:line")),
                tokens=_esc(props.get("aibom:approx_tokens")),
                source=_esc(props.get("aibom:source")),
                owners=_esc(props.get("aibom:owners")) or "—",
                digest=_code((digest or "")[:16] + ("…" if digest else "")),
            )
        )
    lines.append("")
    return lines


def _datasets(datasets: list[dict[str, Any]], retrieval: list[dict[str, Any]]) -> list[str]:
    lines: list[str] = []
    if datasets:
        lines += [
            "## Datasets",
            "",
            "| Dataset | Version | Classification | PII | Sensitive data | Consent | Retention | Jurisdiction | Owners |",
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
        for dataset in datasets:
            props = _prop_map(dataset)
            data = (dataset.get("data") or [{}])[0]
            lines.append(
                "| {name} | {version} | {cls} | {pii} | {sensitive} | {consent} | {retention} | {jur} | {owners} |".format(
                    name=_code(dataset.get("name")),
                    version=_esc(dataset.get("version")),
                    cls=_esc(props.get("aibom:classification")),
                    pii=_yes_no(props.get("aibom:pii")),
                    sensitive=_esc(", ".join(data.get("sensitiveData") or [])),
                    consent=_esc(props.get("aibom:consent_basis")),
                    retention=_esc(props.get("aibom:retention")),
                    jur=_esc(props.get("aibom:jurisdiction")),
                    owners=_esc(props.get("aibom:owners")),
                )
            )
        lines.append("")
    if retrieval:
        lines += [
            "## Retrieval sources",
            "",
            "| Source | Classification | PII | Retention | Refresh |",
            "| --- | --- | --- | --- | --- |",
        ]
        for source in retrieval:
            props = _prop_map(source)
            lines.append(
                "| {name} | {cls} | {pii} | {retention} | {refresh} |".format(
                    name=_code(source.get("name")),
                    cls=_esc(props.get("aibom:classification")),
                    pii=_yes_no(props.get("aibom:pii")),
                    retention=_esc(props.get("aibom:retention")),
                    refresh=_esc(props.get("aibom:refresh")),
                )
            )
        lines.append("")
    return lines


def _ai_sdks(sdks: list[dict[str, Any]]) -> list[str]:
    if not sdks:
        return []
    lines = [
        "## AI SDK versions",
        "",
        "| SDK | Version | Ecosystem | Provider | PURL |",
        "| --- | --- | --- | --- | --- |",
    ]
    for sdk in sdks:
        props = _prop_map(sdk)
        lines.append(
            "| {name} | {version} | {eco} | {provider} | {purl} |".format(
                name=_code(sdk.get("name")),
                version=_code(sdk.get("version")),
                eco=_esc(props.get("aibom:ecosystem")),
                provider=_esc(props.get("aibom:provider")),
                purl=_code(sdk.get("purl")),
            )
        )
    lines.append("")
    return lines


def _dependency_graph(bom: dict[str, Any]) -> list[str]:
    """A Mermaid graph of application → inventory → MCP servers (F-HUMAN-1)."""
    metadata = bom.get("metadata") or {}
    app = metadata.get("component") or {}
    app_ref = app.get("bom-ref")
    if not app_ref:
        return []
    app_ref = str(app_ref)
    deps = {
        d.get("ref"): d.get("dependsOn") or []
        for d in bom.get("dependencies") or []
        if isinstance(d, dict)
    }
    names: dict[str, str] = {app_ref: app.get("name", "app")}
    for item in (bom.get("components") or []) + (bom.get("services") or []):
        if isinstance(item, dict) and item.get("bom-ref"):
            names[str(item["bom-ref"])] = str(item.get("name", item["bom-ref"]))

    def node_id(ref: str) -> str:
        return "n_" + "".join(ch if ch.isalnum() else "_" for ch in ref)

    lines = ["## Dependency graph", "", "```mermaid", "graph LR"]
    lines.append(f'  {node_id(app_ref)}["{_mermaid(app.get("name", "app"))}"]')
    declared: set[str] = set()
    edges: set[tuple[str, str]] = set()
    for ref in [app_ref, *sorted(k for k in deps if k)]:
        if ref not in names:
            continue
        for target in deps.get(ref) or []:
            if target not in names:
                continue
            if (ref, target) in edges:
                continue
            edges.add((ref, target))
            for node in (ref, target):
                if node != app_ref and node not in declared:
                    lines.append(f'  {node_id(node)}["{_mermaid(names[node])}"]')
                    declared.add(node)
            lines.append(f"  {node_id(ref)} --> {node_id(target)}")
    lines += ["```", ""]
    return lines


def _mermaid(text: str) -> str:
    return str(text).replace('"', "'")[:60]


def _review_notes(bom: dict[str, Any]) -> list[str]:
    notes = _collect_review_notes(bom)
    if not notes:
        return ["## Review notes", "", "No findings. ✅", ""]
    errors = [n for n in notes if n["level"] == "error"]
    warnings = [n for n in notes if n["level"] == "warning"]
    infos = [n for n in notes if n["level"] == "info"]
    lines = [
        "## Review notes",
        "",
        f"**{len(errors)} error(s) · {len(warnings)} warning(s) · {len(infos)} info**",
        "",
        "| Level | Code | Subject | Finding |",
        "| --- | --- | --- | --- |",
    ]
    badge = {"error": "🛑 error", "warning": "⚠️ warning", "info": "ℹ️ info"}
    for note in notes:
        lines.append(
            "| {level} | {code} | {subject} | {message} |".format(
                level=badge.get(note["level"], note["level"]),
                code=_code(note["code"]),
                subject=_code(note.get("subject")) if note.get("subject") else "—",
                message=_esc(note["message"])
                + (f" _{note['detail']}_" if note.get("detail") else ""),
            )
        )
    lines.append("")
    return lines


def _collect_review_notes(bom: dict[str, Any]) -> list[dict[str, Any]]:
    """Read review notes back out of the BOM's own properties.

    The BOM only carries note codes (so the JSON stays small and diffable);
    the human message is reconstructed here from a small local table, which
    keeps `render` working from the JSON alone.
    """
    from aibom.risk.review import _CODE_ORDER  # noqa: PLC0415 - local table lookup

    raw: list[tuple[str, str]] = []
    for prop in bom.get("properties") or []:
        if isinstance(prop, dict) and prop.get("name") == "aibom:review_notes":
            for entry in (prop.get("value") or "").split(", "):
                if ":" in entry:
                    level, code = entry.split(":", 1)
                    raw.append((level, code))
    table = _NOTE_MESSAGES
    notes: list[dict[str, Any]] = []
    for level, code in raw:
        message, detail = table.get(code, (code, None))
        notes.append({"level": level, "code": code, "message": message, "detail": detail, "subject": None})
    notes.sort(key=lambda n: _CODE_ORDER.get(n["code"], 500))
    return notes


_NOTE_MESSAGES: dict[str, tuple[str, str | None]] = {
    "system.no_owner": ("The system has no accountable owner.", "Set `system.owner`."),
    "system.no_purpose": ("The system has no stated purpose.", "Set `system.purpose`."),
    "system.no_risk_classification": ("No risk classification recorded.", "Set `system.risk_classification`."),
    "system.no_human_oversight": ("No human-oversight description recorded.", "Set `system.human_oversight`."),
    "model.floating": ("A model alias is not pinned to a dated snapshot.", "Pin the dated snapshot."),
    "model.retired": ("A model in the BOM has retired.", "Replace it."),
    "model.retiring": ("A model in the BOM retires within 90 days.", "Plan the migration."),
    "model.no_purpose": ("A model has no declared purpose.", "Add `models.<alias>.purpose`."),
    "model.no_evals": ("A model has no evaluation reference.", "Add `models.<alias>.evals`."),
    "tool.high_risk_no_hitl": ("A high-risk tool has no human in the loop.", "Add approval or set `human_in_the_loop`."),
    "tool.irreversible_no_hitl": ("An irreversible tool has no human in the loop.", "Declare `human_in_the_loop`."),
    "tool.unknown_risk": ("A tool could not be classified.", "Declare its `risk` and `capabilities`."),
    "tool.risk_override": ("A tool overrides the heuristic risk with no justification.", "Add a `justification`."),
    "mcp.insecure_transport": ("An MCP server uses unencrypted or unauthenticated transport.", "Switch to https with auth."),
    "mcp.unpinned_package": ("An MCP server uses an unpinned package.", "Pin an exact version."),
    "mcp.risk_override": ("An MCP server overrides the heuristic risk with no justification.", "Add a `justification`."),
    "prompt.no_owner": ("A prompt has no owner.", "Add a CODEOWNERS rule or `system.owner`."),
    "dataset.pii_no_consent": ("A dataset holds PII with no consent basis.", "Set `consent_basis`."),
    "dataset.pii_no_retention": ("A dataset holds PII with no retention period.", "Set `retention`."),
    "dataset.no_owner": ("A dataset has no owner.", "Set `owners`."),
    "provider.no_dpa": ("A provider has no recorded data-processing agreement.", "Set `data_processing_agreement: true`."),
    "external.no_dpa": ("An external service has no recorded DPA.", "Set `dpa: true`."),
    "manifest.absent": ("No aibom.yaml found; the BOM is inference-only.", "Run `aibom init`."),
    "lock.stale": ("surface.lock is stale; scanned kinds are `incomplete`.", "Run `aibom generate --refresh`."),
    "ai_sdk.unpinned": ("An AI SDK is not pinned to an exact version.", "Pin it in your lockfile."),
}


def _provenance(bom: dict[str, Any], app_props: dict[str, str], digest: str) -> list[str]:
    metadata = bom.get("metadata") or {}
    tools = metadata.get("tools") or {}
    tool_components = tools.get("components") if isinstance(tools, dict) else None
    tool_text = "—"
    if tool_components:
        tool_text = ", ".join(
            f"{c.get('name')} {c.get('version', '')}".strip() for c in tool_components
        )
    return [
        "---",
        "",
        "## Provenance",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| Git commit | {_code(app_props.get('aibom:git_commit'))} |",
        f"| Git branch | {_code(app_props.get('aibom:git_branch'))} |",
        f"| Git tag | {_code(app_props.get('aibom:git_tag'))} |",
        f"| Working tree | {_esc(app_props.get('aibom:git_dirty'))} |",
        f"| Scanner | {_code(app_props.get('aibom:scanner'))} |",
        f"| Lock | {_code(app_props.get('aibom:lock'))} (fresh: {_esc(app_props.get('aibom:lock_fresh'))}) |",
        f"| Manifest | {_code(app_props.get('aibom:manifest'))} |",
        f"| Generator | {_esc(tool_text)} |",
        f"| Rules version | {_code(app_props.get('aibom:rules_version'))} |",
        f"| CycloneDX | {_esc(bom.get('specVersion'))} |",
        f"| BOM version | {_esc(bom.get('version'))} |",
        f"| Serial number | {_code(bom.get('serialNumber'))} |",
        f"| **Content digest (sha256)** | `{digest}` |",
        "",
        f"Verify this document with `aibom verify {_code('aibom.cdx.json')}`. The digest covers the BOM with "
        "`serialNumber`, `metadata.timestamp` and `version` removed, so it is stable across regenerations.",
        "",
    ]


def render_markdown_from_file(path) -> str:
    data = json.loads(path.read_text(encoding="utf-8"))
    return render_markdown(data)
